/** Gen 1 / Game Boy–inspired nostalgic Pokemon palette */
export const Pokemon = {
  red: '#CC0000',
  blue: '#3B4CCA',
  yellow: '#FFDE00',
  cream: '#FFF8E7',
  parchment: '#F7E0B0',
  navy: '#1D2C5E',
  gbLight: '#9BBC0F',
  gbMid: '#306230',
  gbDark: '#0F380F',
  tan: '#C4A574',
} as const;

export const Mono = {
  black: '#000000',
  white: '#FFFFFF',
  gray100: '#141414',
  gray200: '#1F1F1F',
  gray300: '#2A2A2A',
  gray400: '#444444',
  gray500: '#888888',
  gray600: '#BBBBBB',
} as const;

const tintColorLight = Pokemon.red;

export default {
  light: {
    text: Pokemon.navy,
    background: Pokemon.cream,
    tint: tintColorLight,
    tabIconDefault: Pokemon.tan,
    tabIconSelected: tintColorLight,
    surface: Pokemon.parchment,
    surfaceAlt: '#FFE8A3',
    accent: Pokemon.blue,
    highlight: Pokemon.yellow,
    border: Pokemon.blue,
    heading: Pokemon.red,
    link: Pokemon.blue,
    action: Pokemon.blue,
    actionText: '#FFFFFF',
    actionMuted: Pokemon.gbLight,
    actionMutedText: Pokemon.gbDark,
    danger: Pokemon.red,
    dangerText: '#FFFFFF',
    bubbleMine: Pokemon.blue,
    bubbleMineText: '#FFFFFF',
    spinner: Pokemon.red,
    chartUp: Pokemon.gbLight,
    chartDown: Pokemon.red,
    avatar: Pokemon.blue,
    avatarText: '#FFFFFF',
  },
  dark: {
    text: Mono.white,
    background: Mono.black,
    tint: Mono.white,
    tabIconDefault: Mono.gray500,
    tabIconSelected: Mono.white,
    surface: Mono.gray100,
    surfaceAlt: Mono.gray200,
    accent: Mono.white,
    highlight: Mono.white,
    border: Mono.gray400,
    heading: Mono.white,
    link: Mono.gray600,
    action: Mono.white,
    actionText: Mono.black,
    actionMuted: Mono.gray300,
    actionMutedText: Mono.white,
    danger: Mono.white,
    dangerText: Mono.black,
    bubbleMine: Mono.white,
    bubbleMineText: Mono.black,
    spinner: Mono.white,
    chartUp: Mono.white,
    chartDown: Mono.gray500,
    avatar: Mono.gray300,
    avatarText: Mono.white,
  },
};
