/** Classic Pokemon TCG card-back palette */
export const Pokemon = {
  red: '#D42027',
  blue: '#3B5CA9',
  blueLight: '#7EC8E8',
  bluePale: '#EAF4FC',
  blueSky: '#C5E3F6',
  yellow: '#FFCB05',
  navy: '#1B2B5A',
  navyDeep: '#0F1D47',
  white: '#FFFFFF',
  blueMuted: '#6B8FB8',
  /** @deprecated use bluePale */
  cream: '#EAF4FC',
  /** @deprecated use white */
  parchment: '#FFFFFF',
  tan: '#6B8FB8',
  gbLight: '#C5E3F6',
  gbMid: '#1B2B5A',
  gbDark: '#1B2B5A',
} as const;

export const Mono = {
  black: '#000000',
  white: '#FFFFFF',
  gray100: '#141414',
  gray200: '#1F1F1F',
  gray300: '#2A2A2A',
  gray400: '#444444',
  gray500: '#888888',
  gray600: '#BBBBBB',
} as const;

export default {
  light: {
    text: Pokemon.navy,
    background: Pokemon.bluePale,
    tint: Pokemon.navy,
    tabIconDefault: Pokemon.blueMuted,
    tabIconSelected: Pokemon.navy,
    surface: Pokemon.white,
    surfaceAlt: Pokemon.blueSky,
    accent: Pokemon.blue,
    highlight: Pokemon.yellow,
    border: '#9DC6E8',
    heading: Pokemon.navy,
    link: Pokemon.blue,
    action: Pokemon.yellow,
    actionText: Pokemon.navy,
    actionMuted: Pokemon.blueSky,
    actionMutedText: Pokemon.navy,
    danger: Pokemon.red,
    dangerText: Pokemon.white,
    bubbleMine: Pokemon.blue,
    bubbleMineText: Pokemon.white,
    spinner: Pokemon.red,
    chartUp: Pokemon.blue,
    chartDown: Pokemon.red,
    avatar: Pokemon.blue,
    avatarText: Pokemon.white,
  },
  dark: {
    text: Mono.white,
    background: Mono.black,
    tint: Mono.white,
    tabIconDefault: Mono.gray500,
    tabIconSelected: Mono.white,
    surface: Mono.gray100,
    surfaceAlt: Mono.gray200,
    accent: Mono.white,
    highlight: Mono.white,
    border: Mono.gray400,
    heading: Mono.white,
    link: Mono.gray600,
    action: Mono.white,
    actionText: Mono.black,
    actionMuted: Mono.gray300,
    actionMutedText: Mono.white,
    danger: Mono.white,
    dangerText: Mono.black,
    bubbleMine: Mono.white,
    bubbleMineText: Mono.black,
    spinner: Mono.white,
    chartUp: Mono.white,
    chartDown: Mono.gray500,
    avatar: Mono.gray300,
    avatarText: Mono.white,
  },
};
